#!/bin/bash
name=$(jq -r ".name" data.json | sed 's/.*/\u&/')
formatted_weight=$(jq '.weight / 10' data.json | awk '{printf "%.0f", $1}')
formatted_height=$(jq '.height / 10' data.json | awk '{printf "%.1f", $1}')
type=$(jq -r ".types[].type.name" data.json | sed 's/.*/\u&/')

echo “$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.”
