#!/bin/bash
output_file="pokemon_report.csv"
mkdir -p pokemon_data

echo "Name, Height (m), Weight (kg)" > "$output_file"
for file in pokemon_data/*;do
	name=$(jq -r ".name" "${file}" | sed 's/.*/\u&/')
	formatted_weight=$(jq '.weight / 10' "${file}" | awk '{printf "%.0f", $1}')
	formatted_height=$(jq '.height / 10' "${file}" | awk '{printf "%.1f", $1}')
	
	echo "${name}, ${formatted_height}, ${formatted_weight}" >> "$output_file"
done
echo -e "CSV Report generated at: pokemon_report.csv\n"
cat "$output_file"
echo
awk -F',' '
NR > 1 {
	total_weight += $3;
	total_height += $2;
	count++
}
END {
	if (count > 0) {
		printf "Average Height: %.2f m\n Average Weight: %.2f kg\n", total_weight/count, total_height/count
	} else {
		print "No data found."
	}
}
' "$output_file"
